apiVersion: apps/v1
kind: Deployment
metadata:
  name: feldsher-docs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: feldsher-docs
  template:
    metadata:
      labels:
        app: feldsher-docs
    spec:
      containers:
      - name: feldsher-docs-container
        image: feldsher/docs
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: feldsher-docs-service
spec:
  selector:
    app: feldsher-docs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8000
  type: LoadBalancer
